public enum AGE
{
    AGE_NONE = -1,
    AGE_10, AGE_20, AGE_30, AGE_40, AGE_50, AGE_60
}

public enum QUESTION
{
    Q1, Q2, Q_3, Q_END
}

public enum ANSWER
{
    NONE = -1,
    ANSWER_1, ANSWER_2, ANSWER_3, ANSWER_4
}

public enum GIFTS
{
    NONE = -1, START = 0,
    GUNBAM = 0, STARBUKS, BBASAK, MAGNET, FISHCAKE, BUDS, END
}

public enum SCENE
{
    TITLE, INFORMATION, QUESTION_1, QUESTION_2, QUESTION_3, GIFT, RESULT, MANAGE, END
}

public enum EVENT
{
    DIGITAL, PYTHON, LINUX, SEARCH, SNS, END
}